### ISSUE TITLE
Could not find adapter delegate

### ISSUE THREAD

**Issue by yankeppey** [sockeqwe/AnnotatedAdapter#22]
Hey,
thanks for the library!
do you have any thought why adapter delegate is not being generated sometimes?

> `                                     java.lang.RuntimeException: Could not find adapter delegate for com.buneyeu.myapp.fragment.messages.MessagesAdapter@554b2a1
                                         at com.hannesdorfmann.annotatedadapter.AutoSupportDelegators.getDelegator(AutoSupportDelegators.java:22)
                                         at com.hannesdorfmann.annotatedadapter.support.recyclerview.SupportAnnotatedAdapter.<init>(SupportAnnotatedAdapter.java:36)
                                         at com.buneyeu.myapp.adapters.BaseListAnnotatedAdapter.<init>(BaseListAnnotatedAdapter.java:19)
                                         at com.buneyeu.myapp.fragment.messages.MessagesAdapter.<init>(MessagesAdapter.java:71)
                                         at com.buneyeu.myapp.fragment.messages.MessagesFragment.onCreate(MessagesFragment.java:65)
                                         at com.buneyeu.myapp.fragment.messages.MessagesFragment_.onCreate(MessagesFragment_.java:38)
                                         at android.support.v4.app.Fragment.performCreate(Fragment.java:1939)
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1029)
                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                         at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                         at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
                                         at android.os.Handler.handleCallback(Handler.java:739)
                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                         at android.os.Looper.loop(Looper.java:148)
                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

Clean rebuild helps things, but it's annoying to unexpectedly see the crash. `AutoSupportDelegators` contains, let's say, only 2 of 7-8 annotated adapters.

**Comment by sockeqwe** [comment]
Hi, I guess you are using Android Studio 2.0 and /or  gradle incremental
builds. The problem is that incremental builds break annotation processing.
This basically affects all Annotation processor libraries out there like
dagger etc.

https://github.com/google/dagger/issues/298

Please try to disable incremental builds (see how in the link above) and
let me know if that issue has been caused by incremental builds.

Andrei Buneyeu <notifications@github.com> schrieb am Mi., 24. Feb. 2016,
21:10:
